return {
	"tribela/transparent.nvim",
	lazy = false,
	opts = {
		groups = {
			"Normal",
			"NormalNC",
			"Comment",
			"Constant",
			"Special",
			"Identifier",
			"Statement",
			"PreProc",
			"Type",
			"Underlined",
			"Todo",
			"String",
			"Function",
			"Conditional",
			"Repeat",
			"Operator",
			"Structure",
			"LineNr",
			"NonText",
			"SignColumn",
			"CursorLine",
			"CursorLineNr",
			"StatusLine",
			"StatusLineNC",
			"EndOfBuffer",
		},
		extra_groups = {
			"NormalFloat",
			"FloatBorder",
			"Pmenu",
			"PmenuSel",
			"PmenuSbar",
			"PmenuThumb",
			"NvimTreeNormal",
			"NvimTreeNormalNC",
			"NvimTreeWinSeparator",
			"NeoTreeNormal",
			"NeoTreeNormalNC",
			"NeoTreeWinSeparator",
			"BufferLineBackground",
			"BufferLineFill",
			"BufferLineSeparator",
			"BufferLineSeparatorSelected",
			"LualineNormal",
			"LualineInsert",
			"LualineVisual",
			"LualineReplace",
			"LualineCommand",
			"LualineInactive",
			"WinSeparator",
			"WhichKeyFloat",
			"TelescopeNormal",
			"TelescopeBorder",
			"TelescopePromptBorder",
		},
		exclude_groups = {},
	},
}
